name: PokeAPI Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest tests/unit --html=unit_test_report.html
      - name: Upload unit test report
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_report
          path: unit_test_report.html

  integration_tests:
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Behave integration tests (JSON)
        run: behave -f json -o integration_report.json
      - name: Run Behave integration tests (HTML)
        run: behave --format=behave_html_formatter:HTMLFormatter --outfile=integration_report.html
      - name: Upload integration test reports
        uses: actions/upload-artifact@v3
        with:
          name: integration_reports
          path: |
            integration_report.json
            integration_report.html

  security_tests:
    runs-on: ubuntu-latest
    needs: integration_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Behave security tests (JSON)
        run: behave -f json -o security_report.json
      - name: Run Behave security tests (HTML)
        run: behave --format=behave_html_formatter:HTMLFormatter --outfile=security_report.html
      - name: Upload security test reports
        uses: actions/upload-artifact@v3
        with:
          name: security_reports
          path: |
            security_report.json
            security_report.html

      - name: Run Bandit (static security analysis)
        run: pip install bandit && bandit -r .